language: php
php:
    - 7.3
    - nightly
matrix:
    fast_finish: true
    allow_failures:
        - php: nightly
install:
    - travis_retry composer install --no-interaction
script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/psalm
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
